apiVersion: apps/v1 
kind: ReplicaSet   
metadata: 
  name: replica-set-1
  labels:
    app: replica-set-1
    type: front-end
spec: 
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec: 
      containers:
        - name: busybox-1
          image: busybox
          command: ["/bin/sh", "-ec", "sleep 1000"] # because this image container has nothing to still runing (service)
  replicas: 3 # Here we tell k8s how many replicas we want
  selector: # A label selector field. 
    matchLabels:
      type: front-end