apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  namespace: finance
spec:
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis-container
          image: redis
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
  selector:
    matchLabels:
      app: redis-pod